server:
  port: 8080
  #servlet:
    #contextPath: /construo

logging:
  level:
    ff4j: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/application
    username: postgres
    password: postgres
#    url: jdbc:h2:mem:construo;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:file:./data/h2
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false

security:
  basic:
    enabled: true
    authorize-mode: NONE

redis:
  config:
    host: localhost
    port: 6379

ff4j:
  webconsole:
    enable: true
    url: /ff4j-web-console
    secure: true
    username: sa
    password: sa
    roles: ADMIN
